# fly.toml app configuration file generated for leastcountrush-lax on 2026-09-26T15:23:38Z
#
# See https://docs.fly.io/reference/configuration for information about how to use this file.
#

app = "leastcountrush-lax"
primary_region = 'lax'

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 8080
min_machines_running = 1
processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ['app']
  size = 'shared-cpu-1x'
