# fly.toml app configuration file generated for leastcountrush on 2026-08-09T18:36:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "leastcountrush"
primary_region = "lax"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8080
min_machines_running = 2
processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
  processes = ['app']
  size = 'shared-cpu-1x'
